name: CICD

on:
  push:

permissions:
  contents: read

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    uses: gorgias/reusable-actions/.github/workflows/image-build.yml@main
    with:
      image-names: us-east1-docker.pkg.dev/gorgias-ops-production/container-images/pgbedrock
      docker-file-path: Dockerfile
      build-args: RELEASE=${{ github.sha }}
    secrets: inherit